image: node:12

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
      - images/
      - manifest.json
      - index.html

lint:
  stage: build
  before_script:
    - yarn
  script:
    - yarn lint

pages:
  stage: deploy
  script:
    - mkdir public
    - mv dist index.html images manifest.json public/
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master
  when: manual